### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by UmerFarooqBiomedical** [aron-tn/bounce-checker#1]
Hi Dear,

The program no longer works. Can you please recheck and update the code?

**Error:**
`Traceback (most recent call last):
  File "bounce.py", line 29, in <module>
    bounce(i)
  File "bounce.py", line 18, in bounce
    aa = aa.json()
  File "C:\Python\Python38\lib\site-packages\requests\models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by UmerFarooqBiomedical** [comment]
URL request returns 403 Error.

`<Response [403]>`

**Comment by nemoclipru** [comment]
I also noticed the same problem

**Comment by sunshlne** [comment]
the third party website being used for verification has put a Cloudflare captcha page up. This is why the program appears to have stopped working.

**Comment by UmerFarooqBiomedical** [comment]
> the third party website being used for verification has put a Cloudflare captcha page up. This is why the program appears to have stopped working.

Do you have any other email validator code? Which works fine for domains like aol.com,yahoo.com and hotmail.com.

**Comment by Aron-Tn** [comment]
yup ! i did new one

**Comment by nemoclipru** [comment]
can we already download the new version?

**Comment by Aron-Tn** [comment]
Temporary no

**Comment by nemoclipru** [comment]
> Temporary no

any news?

**Comment by habebaessam12** [comment]
where is the new one?

**Comment by mkdiretc** [comment]
Aron, we still wait your help. I am ready to buy a new version. @mkdirnow
